baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Alquileres Paco'
theme = "HugoTheme-VibrantShadows"
[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'Página de inicio'
  title = 'blog section'
  url = '/Hugo/sites/carrenting/_index.md'
  weight = -110
[[menu.main]]
  identifier = 'barato'
  name = 'Coches Baratos'
  title = 'blog section'
  url = '/Hugo/sites/carrenting/_index.md'
  weight = -10
  [[menu.main]]
  identifier = 'disponibles'
  name = 'Coches Disponibles'
  title = 'blog section'
  url = '/Hugo/sites/carrenting/_index.md'
  weight = -10
  [[menu.main]]
  identifier = 'todos'
  name = 'Nuestros Coches'
  title = 'blog section'
  url = '/Hugo/sites/carrenting/_index.md'
  weight = 10
