baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Alquileres Paco'
theme = "ananke"
[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'Página de inicio'
  title = 'blog section'
  url = '\hugo\Sites\carrenting\content'
  weight = -110
[[menu.main]]
  identifier = 'barato'
  name = 'Coches Baratos'
  title = 'blog section'
  url = 'hugo\Sites\carrenting\content\posts\barato.md'
  weight = -10
  [[menu.main]]
  identifier = 'año'
  name = 'Coches Disponibles'
  title = 'blog section'
  url = 'hugo\Sites\carrenting\content\posts\year.md'
  weight = -10
  [[menu.main]]
  identifier = 'todos'
  name = 'Nuestros Coches'
  title = 'blog section'
  url = 'hugo\Sites\carrenting\content\posts\main.md'
  weight = 10
  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "Tu madre está gorda"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "orange"
  featured_image = "images/header.jpeg"
  
